name = input("Put your name here: ")
age = (input ("Put your age here: "))
favorite_color = input("Put your favorite color here: ")
favorite_movie = input("Put your favorite movie here: ")
mobile_number = int(input ("Put your mobile number here: "))
motto_in_life = input("Put your motto in life here: ")